{{- range .Values.tasks }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ortserver.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ortserver.labels" $ | nindent 4 }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "ortserver.labels" $ | nindent 12 }}
            {{- with $.Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ include "ortserver.fullname" $ }}-tasks-sa
          containers:
            - name: {{ include "ortserver.fullname" $ }}-{{ .name }}-task
              image: "{{ $.Values.containerRegistry }}/ort-server-maintenance-tasks:{{ $.Chart.AppVersion }}"
              env:
                {{- include "ortserver.env.adminSecrets" $ | nindent 16 }}
                {{- include "ortserver.env.database" $ | nindent 16 }}
                {{- include "ortserver.env.fileListStorage" $ | nindent 16 }}
                {{- include "ortserver.env.reportStorage" $ | nindent 16 }}
                {{- include "ortserver.env.typesafeConfigOverride" $ | nindent 16 }}

                # Orchestrator sender
                {{- if $.Values.transport.rabbitmq.enabled }}
                - name: ORCHESTRATOR_SENDER_TRANSPORT_TYPE
                  value: rabbitMQ
                - name: ORCHESTRATOR_SENDER_TRANSPORT_QUEUE_NAME
                  value: {{ $.Values.transport.queues.orchestrator }}
                - name: ORCHESTRATOR_SENDER_TRANSPORT_SERVER_URI
                  value: {{ $.Values.transport.rabbitmq.serverUri }}
                # The RabbitMQ transport does not use the default properties for the credentials.
                - name: CONFIG_FORCE_orchestrator_sender_rabbitMqUser
                  value: {{ $.Values.transport.rabbitmq.username }}
                - name: CONFIG_FORCE_orchestrator_sender_rabbitMqPassword
                  value: {{ $.Values.transport.rabbitmq.password }}
                # - name: ORCHESTRATOR_SENDER_TRANSPORT_USERNAME
                #   value: {{ $.Values.transport.rabbitmq.username }}
                # - name: ORCHESTRATOR_SENDER_TRANSPORT_PASSWORD
                #   value: {{ $.Values.transport.rabbitmq.password }}
                {{- end }}

                # Common task configuration
                - name: TASKS
                  value: "{{ .name }}"
                - name: MONITOR_NAMESPACE
                  value: {{ $.Release.Namespace }}

                # delete-old-ort-runs task
                {{- if eq .name "delete-old-ort-runs" }}
                - name: DATA_RETENTION_ORT_RUN_DAYS
                  value: "{{ .dataRetention.ortRunDays }}"
                {{- end }}

                # delete-orphaned-entities task
                {{- if eq .name "delete-orphaned-entities" }}
                - name: ORPHANED_VCS_INFO_LIMIT
                  value: "{{ .vcsInfo.limit }}"
                - name: ORPHANED_VCS_INFO_CHUNK_SIZE
                  value: "{{ .vcsInfo.chunkSize }}"
                - name: ORPHANED_REMOTE_ARTIFACTS_LIMIT
                  value: "{{ .remoteArtifacts.limit }}"
                - name: ORPHANED_REMOTE_ARTIFACTS_CHUNK_SIZE
                  value: "{{ .remoteArtifacts.chunkSize }}"
                - name: ORPHANED_SNIPPETS_LIMIT
                  value: "{{ .snippets.limit }}"
                - name: ORPHANED_SNIPPETS_CHUNK_SIZE
                  value: "{{ .snippets.chunkSize }}"
                - name: ORPHANED_SNIPPET_FINDINGS_LIMIT
                  value: "{{ .snippetFindings.limit }}"
                - name: ORPHANED_SNIPPET_FINDINGS_CHUNK_SIZE
                  value: "{{ .snippetFindings.chunkSize }}"
                {{- end }}

                # kubernetes-reaper task
                {{- if eq .name "kubernetes-reaper" }}
                - name: MONITOR_REAPER_MAX_AGE
                  value: "{{ .reaperMaxAge }}"
                {{- end }}

                # kubernetes-long-running-jobs-finder task
                {{- if eq .name "kubernetes-long-running-jobs-finder" }}
                - name: MONITOR_TIMEOUT_CONFIG
                  value: "{{ .timeouts.configWorker }}"
                - name: MONITOR_TIMEOUT_ANALYZER
                  value: "{{ .timeouts.analyzerWorker }}"
                - name: MONITOR_TIMEOUT_ADVISOR
                  value: "{{ .timeouts.advisorWorker }}"
                - name: MONITOR_TIMEOUT_SCANNER
                  value: "{{ .timeouts.scannerWorker }}"
                - name: MONITOR_TIMEOUT_EVALUATOR
                  value: "{{ .timeouts.evaluatorWorker }}"
                - name: MONITOR_TIMEOUT_REPORTER
                  value: "{{ .timeouts.reporterWorker }}"
                - name: MONITOR_TIMEOUT_NOTIFIER
                  value: "{{ .timeouts.notifierWorker }}"
                {{- end }}

                # kubernetes-lost-jobs-finder task
                {{- if eq .name "kubernetes-lost-jobs-finder" }}
                - name: MONITOR_LOST_JOBS_MIN_AGE
                  value: "{{ .lostJobsMinAge }}"
                {{- end }}
{{- end }}
