apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ortserver.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ortserver.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ortserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "ortserver.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: ui
    spec:
      serviceAccountName: {{ include "ortserver.fullname" . }}-ui-sa
      {{- include "ortserver.imagePullSecret" . | nindent 6 }}
      containers:
      - name: {{ include "ortserver.fullname" . }}-ui
        image: "{{ .Values.containerRegistry }}/ort-server-ui:{{ .Chart.AppVersion }}"
        ports:
        - containerPort: 8080
        env:
        - name: UI_URL
          value: {{ .Values.ui.url }}
        - name: UI_API_URL
          value: {{ .Values.ui.apiUrl }}
        - name: UI_AUTHORITY
          value: {{ .Values.ui.authority }}
        - name: UI_CLIENT_ID
          value: {{ .Values.ui.clientId }}
