apiVersion: v1
kind: Service
metadata:
  name: {{ include "ortserver.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ortserver.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    {{- include "ortserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
