apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ortserver.fullname" . }}-ui-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ortserver.labels" . | nindent 4 }}
automountServiceAccountToken: false
